export default {
  'JOBS_FETCH_REQUEST': 'JOBS_FETCH_REQUEST',
  'JOBS_FETCH_SUCCESS': 'JOBS_FETCH_SUCCESS',
  'JOBS_FETCH_FAILURE': 'JOBS_FETCH_FAILURE',
  'JOB_ADD_REQUEST': 'JOB_ADD_REQUEST',
  'JOB_ADD_SUCCESS': 'JOB_ADD_SUCCESS',
  'JOB_ADD_FALIURE': 'JOB_ADD_FALIURE',
  'JOB_DELETE_REQUEST': 'JOB_DELETE_REQUEST',
  'JOB_DELETE_SUCCESS': 'JOB_DELETE_SUCCESS',
  'JOB_DELETE_FALIURE': 'JOB_DELETE_FALIURE',
  'TOPICS_FETCH_REQUEST': 'TOPICS_FETCH_REQUEST',
  'TOPICS_FETCH_SUCCESS': 'TOPICS_FETCH_SUCCESS',
  'TOPICS_FETCH_FALIURE': 'TOPICS_FETCH_FALIURE'
};
